namespace: fleet-mc-helm-example
targetCustomizations:
- name: ring0
  helm:
    values:
      replicas: 3
      image:
        tag: 0.0.0
  clusterSelector:
    matchLabels:
      group: ring0
- name: ring1
  helm:
    values:
      image:
        tag: 0.0.1
  clusterSelector:
    matchLabels:
      group: ring1
