namespace: fleet-mc-helm-example
targetCustomizations:
- name: ring0
  helm:
    values:
      replicas: 3
      image:
        tag: v1
  clusterSelector:
    matchLabels:
      group: ring0
- name: ring1
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 1
      image:
        tag: v1
  clusterSelector:
    matchLabels:
      group: ring1
